name: Validate Renovate Config

on:
  pull_request: {}
  push:
    branches:
      - renovate/reconfigure

permissions:
  contents: read

jobs:
  validate-renovate-config:
    name: Validate renovate config
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:44.39.3@sha256:27f008cc48b952dff1fdceed42ef91f243f31e64596dc7f5a8754467961243ad
      options: --user root
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: renovate --version
      - run: renovate-config-validator .github/renovate.json5
